#!/usr/bin/env python3
"""Generate an attack scaffold for an AUTHORIZED agent-security target: an attack.py adapter
(a thin shim to the competition's real AttackAlgorithm interface — filled from its starter code,
since that interface isn't public) and a target_adapter.py stub matching run-redteam-eval's
protocol, both carrying an authorization header. Scaffolds the INTERFACE, not exploit content.

Requires authorization_confirmed in redteam_task.json. Writes <target>_attack/ + a manifest + report.
Exit codes: 0 ok · 3 bad args/IO · 4 refused (unauthorized).

NOTE: helpers here are deliberately self-contained (copied, not imported, across skills).
"""
import argparse
import json
import os
import sys


def die(msg, code):
    print(msg, file=sys.stderr)
    sys.exit(code)


def enforce_authorized_scope(task):
    """Defense-in-depth scope gate (behind the conductor's one-time attestation): the offensive
    skills REFUSE unless the target is an authorized sandbox / harness / owned system. Prose in the
    SKILL is not enough — this puts the refusal in code. Refuses (exit 4) on a missing attestation,
    a target_class outside the allowed set, or a named production product in target_name."""
    allowed_classes = ("kaggle_sandbox", "local_harness", "owned_authorized_system")
    named_products = ("chatgpt", "openai", "gpt-4", "gpt-3", "gpt4", "gemini", "bard", "claude",
                      "anthropic", "copilot", "llama", "grok", "mistral", "perplexity", "deepseek", "qwen")
    if not task.get("authorization_confirmed"):
        die("REFUSED: authorization_confirmed is not true in redteam_task.json — the target must be an "
            "authorized sandbox/competition/owned system, attested via frame-redteam-task, before any attack.", 4)
    tclass = str(task.get("target_class") or "").strip().lower()
    if tclass not in allowed_classes:
        die(f"REFUSED: target_class must be exactly one of {allowed_classes} — got {task.get('target_class')!r}. "
            "Only sandbox/competition/owned targets are in scope; set it in redteam_task.json via frame-redteam-task.", 4)
    name = str(task.get("target_name") or "").lower()
    hit = next((p for p in named_products if p in name), None)
    if hit:
        die(f"REFUSED: target_name {task.get('target_name')!r} looks like a production/real product ('{hit}'). "
            "This pipeline is for authorized sandbox/competition/owned targets ONLY — never production systems, "
            "named products, or other competitors. If this is your OWN sandboxed agent, rename it to drop the "
            "product name.", 4)


AUTH_HEADER = '''\
# ============================================================================
# AUTHORIZED RED-TEAM USE ONLY.
# This scaffold targets the declared sandbox/competition/owned system from redteam_task.json.
# Do NOT use against production/live LLM services, named real products, systems you do not
# own or have explicit permission to test, or other competitors' submissions. Unauthorized
# access is illegal (CFAA and equivalents). Attacks must be deterministic & replayable.
# ============================================================================
'''

ATTACK_TEMPLATE = AUTH_HEADER + '''\
"""attack.py — adapter scaffold generated by scaffold-attack.

The official Kaggle "AI Agent Security - Multi-Step Tool Attacks" AttackAlgorithm interface is
NOT public — CONFIRM it from the competition's starter code and fill the TODOs below. This shim
loads predicate-locked candidate chains from attack_chains.json (build-attack-chains) and replays
them through the competition's env. Keep every candidate deterministic & replayable.
"""
import json

COMP_ID = %%COMP_ID%%


def load_chains(path="attack_chains.json"):
    with open(path) as f:
        return json.load(f).get("chains", [])


class AttackAlgorithm:
    """TODO: match the competition's REAL base class / method names from its starter code."""

    def __init__(self):
        self.chains = load_chains()

    def attack(self, env):
        # TODO: replace with the competition's real interaction API (e.g. env.interact(prompt)).
        # Replay each predicate-locked chain; return replayable candidates. Deterministic only.
        for chain in self.chains:
            for step in chain.get("steps", []):
                _ = step  # env.interact(step)  # <-- wire to the real interface
            # TODO: yield/collect a replayable AttackCandidate per the comp's format.
        return self.chains
'''

TARGET_TEMPLATE = AUTH_HEADER + '''\
"""target_adapter.py — fill this to point run-redteam-eval at your REAL target.

run-redteam-eval expects: run(prompts, predicates) -> {"tool_calls": [{"tool":..., "args":{...}}, ...]}
returned DETERMINISTICALLY. Wire it to your local AgentDojo/InjecAgent harness or the comp sandbox.
(For a quick smoke test of the harness itself, run-redteam-eval has a built-in `--target mock`.)
"""


def run(prompts, predicates):
    # TODO: send `prompts` to your authorized target agent and return the tool calls it made.
    # Must be deterministic (no randomness / external I/O / hidden state) for valid ASR.
    raise NotImplementedError("Wire target_adapter.run() to your authorized sandbox/harness.")
'''


def main():
    ap = argparse.ArgumentParser(description="Scaffold an attack adapter for an authorized agent-security target.")
    ap.add_argument("--task-json", default="redteam_task.json")
    ap.add_argument("--out-dir", default=None)
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()

    if not os.path.exists(args.task_json):
        die(f"{args.task_json} not found — run frame-redteam-task first.", 3)
    with open(args.task_json) as f:
        task = json.load(f)
    enforce_authorized_scope(task)

    target = (task.get("target_name") or "target").replace(" ", "_").lower()
    out_dir = args.out_dir or f"{target}_attack"
    os.makedirs(out_dir, exist_ok=True)
    attack_path = os.path.join(out_dir, "attack.py")
    adapter_path = os.path.join(out_dir, "target_adapter.py")
    if os.path.exists(attack_path) and not args.force:
        die(f"{attack_path} exists — pass --force to overwrite (it may hold your work).", 4)

    comp_id = repr(task.get("comp_id"))  # a valid Python literal even when comp_id is None (json.dumps -> 'null' -> NameError)
    with open(attack_path, "w") as f:
        f.write(ATTACK_TEMPLATE.replace("%%COMP_ID%%", comp_id))
    with open(adapter_path, "w") as f:
        f.write(TARGET_TEMPLATE)

    manifest = {
        "out_dir": os.path.abspath(out_dir),
        "files": ["attack.py", "target_adapter.py"],
        "attack_interface": task.get("attack_interface", "confirm_from_starter_code"),
        "authorization_confirmed": True,
        "comp_id": task.get("comp_id"),
        "notes": "attack.py is a SHIM — confirm the comp's real AttackAlgorithm interface from its starter code and fill the TODOs. "
                 "target_adapter.py wires run-redteam-eval to your real target (or use --target mock to smoke-test the harness).",
    }
    with open(os.path.join(out_dir, "attack_manifest.json"), "w") as f:
        json.dump(manifest, f, indent=2)

    report = f"""# Attack scaffold — {task.get('target_name')}

> 🔒 **Authorized use only** (see the header in every generated file). Deterministic & replayable attacks only.

## At a glance
```mermaid
flowchart LR
    CHAINS["attack_chains.json"] --> ATK["attack.py (shim)"]
    ATK --> ENV["competition env<br/>(confirm interface)"]
    ADP["target_adapter.py"] --> EVAL["run-redteam-eval"]
```

**Generated:** `{attack_path}` (comp shim) · `{adapter_path}` (run-redteam-eval target) · `attack_manifest.json`

## Two TODOs that matter
1. **`attack.py`** — the Kaggle `AttackAlgorithm` interface is not public; confirm it from the comp's starter code and fill the TODOs (replace `env.interact` and the candidate format).
2. **`target_adapter.py`** — wire `run(prompts, predicates)` to your authorized target for real metrics (or use `run-redteam-eval --target mock` to smoke-test the harness first).

## Next
→ `build-attack-chains` (predicate-locked chains) → `run-redteam-eval` (replay + score).
"""
    with open(os.path.join(out_dir, "attack_scaffold_report.md"), "w") as f:
        f.write(report)

    print(f"wrote {attack_path}, {adapter_path}, attack_manifest.json, attack_scaffold_report.md in {out_dir}/")
    print("attack.py is a SHIM — confirm the comp's real interface from its starter code before trusting it.")


if __name__ == "__main__":
    main()
