#!/usr/bin/env python3
"""Defensive counterpart to the red-team: read which attack chains succeeded (redteam_summary.json),
recommend mitigations mapped to the standard intervention stages (text-level / model-level /
execution-level), and optionally emit a DEFENDED target wrapper (an execution-level tool-call
allowlist) so you can re-run run-redteam-eval and measure RESIDUAL ASR on the SAME target + SAME chains.

Writes hardening_summary.json + a report (+ optional defended_target.py). Exit codes: 0 ok · 3 bad args/IO.

HONEST LIMITS (stated in the report): mitigations raise the bar for the tested attacks only — not
immunity from novel attacks; re-eval is the SAME sandbox + SAME chains, and offline ASR ≠ production security.

NOTE: helpers here are deliberately self-contained (copied, not imported, across skills).
"""
import argparse
import json
import os
import sys


def die(msg, code):
    print(msg, file=sys.stderr)
    sys.exit(code)


def fmt(v):
    return "n/a" if v is None else (f"{v:.3f}" if isinstance(v, float) else str(v))


# intervention-stage taxonomy (text / model / execution) — standard PI-defense framing.
MITIGATIONS = [
    ("execution-level", "Tool-call allowlist / least privilege",
     "Permit only the tool calls the legitimate task needs; block or require confirmation for anything else "
     "(e.g. a different recipient, a new tool). Strongest against multi-step tool attacks because it acts at the action, not the text."),
    ("execution-level", "Human-in-the-loop for high-impact actions",
     "Require explicit confirmation before irreversible/external-effect tool calls (send, pay, delete, share)."),
    ("text-level", "Input delimiting / spotlighting of untrusted content",
     "Mark tool outputs / retrieved docs as untrusted and instruct the model to never follow instructions found inside them."),
    ("text-level", "Injection detection / sanitization",
     "Screen tool outputs for instruction-like content before they re-enter the context; strip or flag them."),
    ("model-level", "Instruction hierarchy",
     "Train/configure the agent so system + user intent strictly outrank instructions embedded in tool data."),
]


DEFENDED_TEMPLATE = '''\
"""defended_target.py — generated by harden-agent.
Execution-level defense: wraps a base target and permits ONLY tool calls on the benign allowlist;
all other tool calls are blocked. Re-run: run-redteam-eval --target defended_target.py to measure residual ASR.
This is a DEMO mitigation to close the find->fix loop; it is not a production defense, and it does not
generalize beyond the chains/target it was measured on."""
import importlib.util
import os

BASE = %%BASE%%          # "mock" or a path to a base adapter .py
ALLOW = %%ALLOW%%        # list of permitted {"tool":..., "args":{...}} (the benign task's tool calls)


def _mock(prompts, predicates):
    text = "\\n".join(prompts)
    calls = []
    for spec in (predicates or {}).values():
        tool = spec.get("tool")
        if tool and tool in text:
            args = {k: v for k, v in (spec.get("args_contains") or {}).items() if str(v) in text}
            if args or not spec.get("args_contains"):
                calls.append({"tool": tool, "args": args})
    return {"tool_calls": calls}


def _base_run(prompts, predicates):
    if BASE == "mock":
        return _mock(prompts, predicates)
    spec = importlib.util.spec_from_file_location("base_target", BASE)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod.run(prompts, predicates)


def _allowed(call):
    args = call.get("args") if isinstance(call.get("args"), dict) else {}
    for a in ALLOW:
        if call.get("tool") == a.get("tool") and all(str(args.get(k)) == str(v)
                                                      for k, v in (a.get("args") or {}).items()):
            return True
    return False


def run(prompts, predicates):
    out = _base_run(prompts, predicates)
    kept = [c for c in out.get("tool_calls", []) if _allowed(c)]
    return {"tool_calls": kept, "blocked": [c for c in out.get("tool_calls", []) if not _allowed(c)]}
'''


def main():
    ap = argparse.ArgumentParser(description="Recommend mitigations + emit a defended target to re-measure residual ASR.")
    ap.add_argument("--summary", default="redteam_summary.json")
    ap.add_argument("--task-json", default="redteam_task.json")
    ap.add_argument("--emit-defense", action="store_true", help="write defended_target.py (execution-level allowlist demo)")
    args = ap.parse_args()

    if not os.path.exists(args.summary):
        die(f"{args.summary} not found — run run-redteam-eval first.", 3)
    with open(args.summary) as f:
        summ = json.load(f)
    task = {}
    if os.path.exists(args.task_json):
        with open(args.task_json) as f:
            task = json.load(f)

    asr = summ.get("targeted_asr")
    succeeded = [c for c in summ.get("per_chain", []) if c.get("unsafe_triggered")]

    emitted = None
    if args.emit_defense:
        preds = task.get("predicates") or {}
        benign = preds.get("benign_success") or {}
        allow = [{"tool": benign.get("tool"), "args": benign.get("args_contains", {})}] if benign.get("tool") else []
        base = json.dumps(summ.get("target_adapter", "mock"))
        src = DEFENDED_TEMPLATE.replace("%%BASE%%", base).replace("%%ALLOW%%", json.dumps(allow))
        with open("defended_target.py", "w") as f:
            f.write(src)
        emitted = "defended_target.py"

    out = {
        "baseline_targeted_asr": asr,
        "chains_succeeded": [c.get("id") for c in succeeded],
        "recommendations": [{"stage": s, "name": n, "detail": d} for s, n, d in MITIGATIONS],
        "defended_target": emitted,
        "residual_asr": None,
        "scope": "Re-evaluation must use the SAME target + SAME chains. Mitigations raise the bar for the tested "
                 "attacks only — not immunity from novel attacks. Offline ASR ≠ production security.",
        "notes": "",
    }
    with open("hardening_summary.json", "w") as f:
        json.dump(out, f, indent=2)

    rec_rows = "\n".join(f"| {s} | {n} | {d} |" for s, n, d in MITIGATIONS)
    remeasure = (f"\n## Re-measure residual ASR\nA defended target was written to `{emitted}` (execution-level allowlist). "
                 f"Re-run the SAME chains against it:\n```bash\n.venv/bin/python \"${{CLAUDE_PLUGIN_ROOT}}/skills/run-redteam-eval/scripts/run_redteam_eval.py\" "
                 f"--target {emitted} --chains attack_chains.json --task-json {args.task_json}\n```\nCompare its Targeted ASR to the baseline {fmt(asr)} above. "
                 f"A drop shows the mitigation works **against these chains on this target** — not in general.\n") if emitted else ""
    report = f"""# Hardening — {summ.get('target_name')}

> ⚠️ Mitigations below raise the bar for the **tested** attacks only — not immunity from novel ones. Any re-evaluation is the **same sandbox + same chains**. **Offline ASR ≠ production security.**

## At a glance
```mermaid
flowchart LR
    ASR["baseline Targeted ASR<br/>{fmt(asr)}"] --> MIT["mitigations<br/>text · model · execution"]
    MIT --> RES["re-measure residual ASR<br/>(same target + chains)"]
```

**Baseline Targeted ASR:** {fmt(asr)} · **chains that succeeded:** {', '.join(c.get('id') for c in succeeded) or 'none'}

## Recommended mitigations (by intervention stage)
| stage | mitigation | why |
|---|---|---|
{rec_rows}
{remeasure}
## Next
→ Adopt a mitigation, re-run `run-redteam-eval` on the defended target, and report the residual ASR. The decision to adopt is the human's.
"""
    with open("hardening_report.md", "w") as f:
        f.write(report)

    print(f"baseline Targeted ASR {fmt(asr)} · {len(succeeded)} chains succeeded · "
          + (f"emitted {emitted}" if emitted else "no defense emitted (pass --emit-defense)"))
    print("wrote hardening_summary.json + hardening_report.md")


if __name__ == "__main__":
    main()
