#!/usr/bin/env python3
"""scaffold-train: generate a RUNNABLE Ultralytics YOLO detection training bundle — then STOP.

It scaffolds the harness, it does NOT train a competitive model. Real training is GPU-hours (both Ultralytics
and MMDetection say CPU training is too slow to be competitive). This script:
  - Builds a COCO -> 0-based-contiguous CLASS MAP (class_map.json) shared by train/eval/submission — never the
    naive `category_id - 1`, which is wrong for non-contiguous COCO ids.
  - Generates prepare_data.py (COCO->YOLO labels + PER-IMAGE 16-bit->8-bit normalization into a canonical
    images/{train,val} + labels/{train,val} tree — YOLO finds labels by the /images/->/labels/ path swap, so
    the layout is load-bearing), data.yaml (points at the CONVERTED images, never the raw 16-bit source),
    train.py + train_config.yaml (config-driven), predict.py (emits the pipeline's predictions schema from
    boxes.xyxy, never the center-based boxes.xywh), and a version-pinned requirements.txt.
  - Runs a CPU SMOKE test that (a) runs the real prepare_data.py on a tiny subset, (b) ASSERTS YOLO loaded > 0
    labels (a green smoke on 0 labels is meaningless), (c) if ultralytics is installed, runs 1 CPU epoch into a
    quarantined smoke_throwaway/ dir. The bundle still generates if ultralytics is absent.

The manifest carries NEGATIVE assertions (produces_trained_model:false, weights_are_throwaway:true) so no
downstream skill or auto-report can render a smoke run as a real result.

Exit codes: 0 ok · 2 dependency/IO issue · 3 bad/missing input · 4 refused.

NOTE: helpers here are deliberately self-contained (the plugin copies helpers byte-identical across scripts).
"""
import argparse
import json
import os
import subprocess
import sys


def die(msg, code):
    print(msg, file=sys.stderr)
    sys.exit(code)


def eprint(*a, **k):
    print(*a, file=sys.stderr, **k)


def is_leaky_provenance(prov):
    """True if a split_summary provenance marks a leaky (per-image, acked) split — the single honesty stamp
    downstream skills must not silently drop if the provenance string is ever renamed."""
    return str(prov).startswith("per-image")


# ---------------------------------------------------------------------------
# Generated bundle scripts (static templates — configs carry the paths/values).
# ---------------------------------------------------------------------------
PREPARE_DATA = r'''#!/usr/bin/env python3
"""Generated by scaffold-train. COCO -> YOLO label conversion + PER-IMAGE 16-bit->8-bit normalization.
Reads prepare_config.json. Writes <dest>/images/{split}/<stem>.png (8-bit RGB) and
<dest>/labels/{split}/<stem>.txt (YOLO: `cls cx cy w h`, normalized to [0,1], 0-based REMAPPED class ids).
Emits <dest>/normalization_report.json.

16-bit -> 8-bit compresses 65536 -> 256 levels; faint objects near the noise floor may be lost. Normalization
statistics are PER IMAGE (percentile), never dataset-global — a global fit would leak val stats into train.
"""
import argparse, json, os, sys


def load_ids(path):
    with open(path) as f:
        return [ln.strip() for ln in f if ln.strip()]


def to_uint8(arr, low, high):
    import numpy as np
    a = arr.astype("float64")
    lo, hi = np.percentile(a, [low, high])
    if hi <= lo:
        lo, hi = float(a.min()), float(a.max())
    if hi <= lo:
        return np.zeros(a.shape, "uint8")
    return (np.clip((a - lo) / (hi - lo), 0.0, 1.0) * 255.0).astype("uint8")


EXTS = (".png", ".jpg", ".jpeg", ".tif", ".tiff", ".bmp", ".fits", ".fit", ".fts")


def build_image_index(images_dir):
    """One os.walk -> {stem: path}. Avoids re-walking the whole dir once per image (O(N^2) on big datasets).
    First match per stem wins (files sorted) so a repeated stem resolves deterministically."""
    idx = {}
    for root, _d, files in os.walk(images_dir):
        for fn in sorted(files):
            if fn.lower().endswith(EXTS):
                idx.setdefault(os.path.splitext(fn)[0], os.path.join(root, fn))
    return idx


def load_source(path):
    """Return (array, is_color). An 8-bit 3-channel image is preserved as RGB (no lossy grayscale collapse);
    single-channel or high-bit-depth data (astronomical 16-bit, FITS) comes back 2-D float32 for the per-image
    normalization path."""
    ext = os.path.splitext(path)[1].lower()
    import numpy as np
    if ext in (".fits", ".fit", ".fts"):
        from astropy.io import fits
        with fits.open(path) as h:
            data = next((x.data for x in h if getattr(x, "data", None) is not None), None)
        if data is None:
            raise ValueError("no image data in any FITS HDU")
        arr = np.asarray(data).astype("float32")
        if arr.ndim > 2:
            arr = arr[tuple([0] * (arr.ndim - 2))]
        return arr, False
    from PIL import Image
    with Image.open(path) as im:
        arr = np.asarray(im)
    if arr.ndim == 3 and arr.shape[2] >= 3 and arr.dtype == np.uint8:
        return arr[:, :, :3], True
    arr = arr.astype("float32")
    if arr.ndim == 3:
        arr = arr.mean(axis=2)
    return arr, False


def main():
    import numpy as np
    from PIL import Image
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", default="prepare_config.json")
    ap.add_argument("--limit", type=int, default=0, help="cap images per split (smoke test); 0 = all")
    args = ap.parse_args()
    cfg = json.load(open(args.config))
    dest = cfg["dest"]
    low, high = cfg["normalization"]["low"], cfg["normalization"]["high"]
    cmap = {int(k): int(v) for k, v in cfg["coco_id_to_yolo"].items()}

    coco = json.load(open(cfg["annotations"]))
    by_id = {img["id"]: img for img in coco["images"]}
    stem_to_img = {os.path.splitext(img.get("file_name", str(img["id"])))[0]: img for img in coco["images"]}
    anns_by_stem = {}
    for a in coco.get("annotations", []):
        img = by_id.get(a["image_id"])
        if img is None:
            continue
        st = os.path.splitext(img.get("file_name", str(img["id"])))[0]
        anns_by_stem.setdefault(st, []).append(a)

    total_boxes, total_imgs, skipped_cat, missing, failed, color_kept = 0, 0, 0, [], [], 0
    index = build_image_index(cfg["images_dir"])
    for split, ids_path in (("train", cfg["train_ids"]), ("val", cfg["val_ids"])):
        ids = load_ids(ids_path)
        if args.limit:
            ids = ids[:args.limit]
        img_out = os.path.join(dest, "images", split)
        lbl_out = os.path.join(dest, "labels", split)
        os.makedirs(img_out, exist_ok=True)
        os.makedirs(lbl_out, exist_ok=True)
        for stem in ids:
            src = index.get(stem)
            if src is None:
                missing.append(stem)
                continue
            try:
                arr, is_color = load_source(src)
                if is_color:
                    rgb = arr                       # already 8-bit RGB — preserve color
                    color_kept += 1
                else:
                    u8 = to_uint8(arr, low, high)   # 16-bit/grayscale -> per-image 8-bit
                    rgb = np.stack([u8, u8, u8], axis=-1)  # 3-channel for RGB-pretrained backbones
                Image.fromarray(rgb.astype("uint8"), "RGB").save(os.path.join(img_out, stem + ".png"))
            except Exception as e:
                failed.append(f"{stem}: {type(e).__name__}: {e}")
                continue
            H, W = arr.shape[:2]
            meta = stem_to_img.get(stem, {})
            W = int(meta.get("width", W)); H = int(meta.get("height", H))
            lines = []
            for a in anns_by_stem.get(stem, []):
                if a.get("category_id") not in cmap:
                    skipped_cat += 1
                    continue
                bb = a.get("bbox")
                if not (isinstance(bb, (list, tuple)) and len(bb) == 4):
                    continue
                x, y, w, h = [float(v) for v in bb]
                cx, cy = (x + w / 2.0) / W, (y + h / 2.0) / H
                lines.append(f"{cmap[a['category_id']]} {cx:.6f} {cy:.6f} {w / W:.6f} {h / H:.6f}")
                total_boxes += 1
            with open(os.path.join(lbl_out, stem + ".txt"), "w") as f:
                f.write("\n".join(lines) + ("\n" if lines else ""))
            total_imgs += 1

    report = {"images_written": total_imgs, "boxes_written": total_boxes,
              "annotations_skipped_unknown_category": skipped_cat, "images_missing": missing[:20],
              "n_images_missing": len(missing), "images_failed": failed[:20], "n_images_failed": len(failed),
              "color_preserved_rgb": color_kept, "normalized_to_8bit": total_imgs - color_kept,
              "normalization": cfg["normalization"],
              "note": "8-bit RGB images are preserved as color; single-channel/16-bit are per-image normalized to "
                      "8-bit (lossy: 65536->256 levels, faint objects may be lost). Stats are per-image, not "
                      "dataset-global."}
    os.makedirs(dest, exist_ok=True)
    json.dump(report, open(os.path.join(dest, "normalization_report.json"), "w"), indent=2)
    print(f"prepare_data: {total_imgs} images ({color_kept} color, {total_imgs - color_kept} normalized), "
          f"{total_boxes} boxes -> {dest}/{{images,labels}}/  "
          f"(missing={len(missing)}, failed={len(failed)}, skipped_cat={skipped_cat})")
    if missing:
        print(f"  WARNING: {len(missing)} split ids had no image file (e.g. {missing[:3]})", file=sys.stderr)
    if failed:
        print(f"  WARNING: {len(failed)} image(s) failed to load/convert (e.g. {failed[:2]})", file=sys.stderr)


if __name__ == "__main__":
    main()
'''

TRAIN_PY = r'''#!/usr/bin/env python3
"""Generated by scaffold-train. REAL TRAINING — RUN THIS ON A GPU. Reads train_config.yaml (config-driven).
A CPU run only proves the pipeline executes; it does NOT produce a competitive model (Ultralytics/MMDetection
both call CPU training too slow). Run prepare_data.py FIRST so images/ and labels/ exist."""
import sys
from pathlib import Path

HERE = Path(__file__).parent
try:
    import yaml
    from ultralytics import YOLO
except Exception:
    sys.exit("Install deps first: pip install -r requirements.txt")
cfg = yaml.safe_load(open(HERE / "train_config.yaml"))
YOLO(cfg["model"]).train(
    data=str(HERE / "data.yaml"),
    epochs=int(cfg["epochs"]), imgsz=int(cfg["imgsz"]), batch=cfg["batch"],
    device=cfg["device"], project=cfg.get("project", "runs"), name=cfg.get("name", "train"),
)
print("Training done. Weights under", cfg.get("project", "runs"), "/", cfg.get("name", "train"), "/weights/best.pt")
'''

PREDICT_PY = r'''#!/usr/bin/env python3
"""Generated by scaffold-train. Inference -> predictions in the pipeline's schema for evaluate-detection and
make-detection-submission. image_id = file STEM; class_id = 0-based YOLO id (decode via class_map.json);
x,y,w,h = TOP-LEFT PIXELS derived from boxes.xyxy (NEVER boxes.xywh, which is CENTER-based -> half-box shift)."""
import argparse, csv, sys
from pathlib import Path
try:
    from ultralytics import YOLO
except Exception:
    sys.exit("pip install ultralytics to run inference")
ap = argparse.ArgumentParser()
ap.add_argument("--weights", required=True)
ap.add_argument("--images", required=True, help="dir of images to predict on")
ap.add_argument("--out", default="preds.csv")
ap.add_argument("--conf", type=float, default=0.001, help="low by default so evaluate can build a full PR curve")
args = ap.parse_args()
rows = []
for r in YOLO(args.weights).predict(args.images, conf=args.conf, stream=True, verbose=False):
    b = r.boxes
    if b is None:
        continue
    xyxy = b.xyxy.cpu().numpy(); sc = b.conf.cpu().numpy(); cl = b.cls.cpu().numpy().astype(int)
    stem = Path(r.path).stem
    for (x1, y1, x2, y2), s, c in zip(xyxy, sc, cl):
        rows.append([stem, int(c), float(s), float(x1), float(y1), float(x2 - x1), float(y2 - y1)])
with open(args.out, "w", newline="") as f:
    w = csv.writer(f); w.writerow(["image_id", "class_id", "score", "x", "y", "w", "h"]); w.writerows(rows)
print(f"wrote {len(rows)} predictions -> {args.out}")
'''


def build_class_map(coco):
    cats = coco.get("categories", [])
    if not cats:
        die("COCO annotations have no categories[] — cannot build a class map.", 3)
    ids = sorted({c["id"] for c in cats})
    name_by_id = {c["id"]: c.get("name", str(c["id"])) for c in cats}
    coco_id_to_yolo = {cid: i for i, cid in enumerate(ids)}
    names = {i: name_by_id[cid] for cid, i in coco_id_to_yolo.items()}
    return {"coco_id_to_yolo": {str(k): v for k, v in coco_id_to_yolo.items()},
            "yolo_to_name": {str(i): n for i, n in names.items()},
            "names_ordered": [names[i] for i in range(len(names))]}


def resolve_split_dir(splits_dir, fold):
    """splits_dir may be a single holdout (train_ids.txt at root) or k-fold (fold_N/). Return the dir holding
    train_ids.txt/val_ids.txt for the requested fold."""
    root = os.path.join(splits_dir, "train_ids.txt")
    if os.path.exists(root):
        return splits_dir
    fdir = os.path.join(splits_dir, f"fold_{fold}")
    if os.path.exists(os.path.join(fdir, "train_ids.txt")):
        return fdir
    die(f"no train_ids.txt in {splits_dir} (holdout) or {splits_dir}/fold_{fold}/ — run split-images first.", 3)


def write_yaml_names(bundle_abs, names_ordered):
    lines = ["# Generated by scaffold-train. Paths point at the CONVERTED 8-bit images (images/{train,val}),",
             "# NEVER the raw 16-bit source. Run prepare_data.py before training so these dirs exist.",
             f"path: {bundle_abs}", "train: images/train", "val: images/val", "names:"]
    lines += [f"  {i}: {n}" for i, n in enumerate(names_ordered)]
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description="Scaffold a runnable Ultralytics YOLO detection training bundle.")
    ap.add_argument("--images", required=True, help="directory of source images (may be 16-bit)")
    ap.add_argument("--annotations", required=True, help="COCO annotations json")
    ap.add_argument("--splits", required=True, help="image_splits/ from split-images")
    ap.add_argument("--fold", type=int, default=0, help="which fold to scaffold (k-fold splits only)")
    ap.add_argument("--task", default="detect", choices=["detect"], help="detection only for now")
    ap.add_argument("--model", default="yolo11n.pt", help="pretrained checkpoint (transfer learning)")
    ap.add_argument("--imgsz", type=int, default=640)
    ap.add_argument("--epochs", type=int, default=100)
    ap.add_argument("--batch", default=16)
    ap.add_argument("--device", default="0", help="real-training device (GPU id). The smoke test always uses cpu.")
    ap.add_argument("--ultralytics-version", default="8.3.0", help="version pinned in requirements.txt")
    ap.add_argument("--out-dir", default="cv_train_scaffold")
    ap.add_argument("--no-smoke", action="store_true", help="skip the CPU smoke test")
    ap.add_argument("--smoke-imgsz", type=int, default=320)
    ap.add_argument("--smoke-n", type=int, default=4, help="images per split for the smoke test")
    ap.add_argument("--force", action="store_true")
    args = ap.parse_args()

    for p, what in ((args.images, "--images dir"), (args.annotations, "--annotations"), (args.splits, "--splits dir")):
        if not os.path.exists(p):
            die(f"{what} not found: {p}", 3)
    try:
        coco = json.load(open(args.annotations))
    except Exception as e:
        die(f"could not parse COCO annotations: {e}", 3)

    bundle = args.out_dir
    if os.path.exists(os.path.join(bundle, "train.py")) and not args.force:
        die(f"{bundle}/train.py exists — pass --force to overwrite.", 4)
    os.makedirs(bundle, exist_ok=True)
    bundle_abs = os.path.abspath(bundle)

    split_dir = resolve_split_dir(args.splits, args.fold)
    split_summary = {}
    ss_path = os.path.join(args.splits, "split_summary.json")
    if os.path.exists(ss_path):
        split_summary = json.load(open(ss_path))

    cmap = build_class_map(coco)
    json.dump(cmap, open(os.path.join(bundle, "class_map.json"), "w"), indent=2)

    prepare_config = {
        "images_dir": os.path.abspath(args.images),
        "annotations": os.path.abspath(args.annotations),
        "train_ids": os.path.abspath(os.path.join(split_dir, "train_ids.txt")),
        "val_ids": os.path.abspath(os.path.join(split_dir, "val_ids.txt")),
        "dest": bundle_abs,
        "coco_id_to_yolo": cmap["coco_id_to_yolo"],
        "normalization": {"method": "per_image_percentile", "low": 1.0, "high": 99.0},
    }
    json.dump(prepare_config, open(os.path.join(bundle, "prepare_config.json"), "w"), indent=2)

    with open(os.path.join(bundle, "prepare_data.py"), "w") as f:
        f.write(PREPARE_DATA)
    with open(os.path.join(bundle, "train.py"), "w") as f:
        f.write(TRAIN_PY)
    with open(os.path.join(bundle, "predict.py"), "w") as f:
        f.write(PREDICT_PY)
    with open(os.path.join(bundle, "data.yaml"), "w") as f:
        f.write(write_yaml_names(bundle_abs, cmap["names_ordered"]))
    train_cfg = (f"# Generated by scaffold-train. Edit + run train.py ON A GPU.\n"
                 f"model: {args.model}\nepochs: {args.epochs}\nimgsz: {args.imgsz}\nbatch: {args.batch}\n"
                 f"device: {args.device}   # GPU id for real training; the smoke test forces cpu\n"
                 f"project: runs\nname: {args.task}_yolo\n")
    with open(os.path.join(bundle, "train_config.yaml"), "w") as f:
        f.write(train_cfg)
    with open(os.path.join(bundle, "requirements.txt"), "w") as f:
        f.write(f"# Pinned — Ultralytics APIs drift across versions.\nultralytics=={args.ultralytics_version}\n")

    smoke = run_smoke(bundle, bundle_abs, prepare_config, args) if not args.no_smoke else \
        {"executed": False, "reason": "--no-smoke"}

    n_classes = len(cmap["names_ordered"])
    manifest = {
        "bundle_path": bundle_abs,
        "task": args.task,
        "model": args.model,
        "n_classes": n_classes,
        "class_map": "class_map.json",
        "data_yaml": "data.yaml",
        "fold_used": os.path.relpath(split_dir, args.splits),
        "split_provenance": split_summary.get("split_provenance", "UNKNOWN"),
        "leakage_ack": split_summary.get("leakage_ack"),
        "pinned": {"ultralytics": args.ultralytics_version},
        "produces_trained_model": False,
        "weights_are_throwaway": True,
        "smoke": smoke,
        "generated_scripts": ["prepare_data.py", "train.py", "predict.py"],
        "run_order": ["python prepare_data.py --config prepare_config.json",
                      "python train.py   # ON A GPU",
                      "python predict.py --weights runs/*/weights/best.pt --images <test_dir> --out preds.csv"],
        "boundary": "This is a SCAFFOLD, not a trained model. The CPU smoke test only proves the pipeline runs. "
                    "Real training is GPU-hours; a local smoke result is NOT a leaderboard result and the smoke "
                    "weights under smoke_throwaway/ are throwaway.",
    }
    json.dump(manifest, open(os.path.join(bundle, "train_scaffold_manifest.json"), "w"), indent=2)
    write_report(bundle, manifest)

    print(f"Wrote YOLO training bundle -> {bundle}/ (class_map, prepare_data.py, train.py, predict.py, "
          f"data.yaml, train_config.yaml, requirements.txt)")
    print(smoke_line(smoke))
    if is_leaky_provenance(manifest["split_provenance"]):
        eprint("  WARNING: split provenance is PER-IMAGE (acked leaky) — any metric from this model is inflated.")


def run_smoke(bundle, bundle_abs, prepare_config, args):
    """Run the REAL prepare_data.py on a tiny subset into a quarantined smoke_throwaway/, assert >0 labels
    loaded, then (if ultralytics is present) 1 CPU epoch. Honest about download/AMP/offline failures."""
    smoke_dir = os.path.join(bundle, "smoke_throwaway")
    os.makedirs(smoke_dir, exist_ok=True)
    smoke_cfg = dict(prepare_config)
    smoke_cfg["dest"] = os.path.abspath(smoke_dir)
    json.dump(smoke_cfg, open(os.path.join(smoke_dir, "prepare_config.json"), "w"), indent=2)

    prep = subprocess.run(
        [sys.executable, os.path.join(bundle, "prepare_data.py"),
         "--config", os.path.join(smoke_dir, "prepare_config.json"), "--limit", str(args.smoke_n)],
        capture_output=True, text=True)
    if prep.returncode != 0:
        return {"executed": True, "executed_without_error": False, "labels_loaded": 0,
                "stage": "prepare_data", "error": (prep.stderr or prep.stdout or "").strip()[:500]}

    labels_loaded = 0
    for split in ("train", "val"):
        ld = os.path.join(smoke_dir, "labels", split)
        if os.path.isdir(ld):
            for fn in os.listdir(ld):
                try:
                    with open(os.path.join(ld, fn)) as f:
                        labels_loaded += sum(1 for ln in f if ln.strip())
                except OSError:
                    pass
    if labels_loaded == 0:
        return {"executed": True, "executed_without_error": False, "labels_loaded": 0, "stage": "prepare_data",
                "error": "prepare_data wrote 0 label boxes for the smoke subset — YOLO would train on nothing. "
                         "Check that the split ids have annotations and category_ids match the class map."}

    # write a smoke data.yaml pointing at the throwaway tree
    with open(os.path.join(smoke_dir, "data.yaml"), "w") as f:
        f.write(write_yaml_names(os.path.abspath(smoke_dir), json.load(
            open(os.path.join(bundle, "class_map.json")))["names_ordered"]))

    try:
        from ultralytics import YOLO
    except Exception:
        return {"executed": True, "executed_without_error": True, "labels_loaded": labels_loaded,
                "trained": False,
                "reason": "ultralytics not installed (`.venv/bin/pip install ultralytics` to run the CPU epoch)"}
    try:
        YOLO(args.model).train(
            data=os.path.join(smoke_dir, "data.yaml"), epochs=1, imgsz=args.smoke_imgsz, device="cpu",
            amp=False, cache=False, plots=False, verbose=False, workers=0,
            project=os.path.abspath(smoke_dir), name="run", exist_ok=True)
        return {"executed": True, "executed_without_error": True, "labels_loaded": labels_loaded,
                "trained": True, "epochs": 1, "device": "cpu",
                "note": "1 CPU epoch on a few images — proves the pipeline runs; NOT a model. Delete smoke_throwaway/."}
    except Exception as e:
        return {"executed": True, "executed_without_error": False, "labels_loaded": labels_loaded, "trained": False,
                "stage": "yolo_train", "error": f"{type(e).__name__}: {e}"[:500],
                "hint": "Often a weights download / AMP check needing network, or a torch/ultralytics version issue. "
                        "The BUNDLE still generated — run train.py where deps + a GPU are available."}


def smoke_line(s):
    if not s.get("executed"):
        return f"Smoke test: not run ({s.get('reason', 'skipped')})."
    if not s.get("executed_without_error"):
        return f"Smoke test: ❌ FAILED at {s.get('stage', '?')} — {s.get('error', '')[:160]}"
    if s.get("trained"):
        return (f"Smoke test: ✅ executed — prepared data, loaded {s['labels_loaded']} label boxes, ran 1 CPU epoch. "
                "This PROVES the pipeline runs; it is NOT a trained model (throwaway weights in smoke_throwaway/).")
    return (f"Smoke test: ⚠️ partial — data prepared, {s['labels_loaded']} label boxes asserted (>0 ✓); "
            f"no CPU epoch ran — {s.get('reason', 'training step skipped')}.")


def write_report(bundle, m):
    s = m["smoke"]
    prov = m["split_provenance"]
    prov_badge = ("🔴 PER-IMAGE (leaky)" if is_leaky_provenance(prov)
                  else ("🟢 " + str(prov)) if prov != "UNKNOWN" else "❓ UNKNOWN")
    md = f"""# YOLO training scaffold — {m['task']} ({m['n_classes']} classes)

## At a glance
```mermaid
flowchart LR
    P["prepare_data.py<br/>COCO→YOLO + 16-bit→8-bit"] --> D["data.yaml<br/>→ converted images/"]
    D --> T["train.py<br/>🖥️ ON YOUR GPU"]
    T --> W["best.pt"]
    W --> PR["predict.py<br/>→ preds.csv"]
    SMOKE["CPU smoke: {('ran 1 epoch' if s.get('trained') else 'data prepared, no train' if s.get('executed_without_error') else 'FAILED — see report')}"] -.->|throwaway| T
```

- **Bundle:** `{m['bundle_path']}`
- **Split provenance:** {prov_badge}  ·  **produces_trained_model: `false`**  ·  weights_are_throwaway: `true`
- **Smoke test:** {smoke_line(s)}
- **Pinned:** ultralytics=={m['pinned']['ultralytics']} (APIs drift — keep it pinned)

## Run order (real training is YOURS to run, on a GPU)
```bash
cd {os.path.basename(m['bundle_path'])}
pip install -r requirements.txt
python prepare_data.py --config prepare_config.json   # writes images/ + labels/ (normalizes 16-bit)
python train.py                                        # 🖥️ GPU-hours — edit train_config.yaml first
python predict.py --weights runs/*/weights/best.pt --images <test_dir> --out preds.csv
```

## What this is / isn't
- ✅ A runnable, config-driven YOLO transfer-learning harness with leakage-safe converted data.
- ✅ 16-bit is normalized PER IMAGE to 8-bit before YOLO (never silently truncated); loss is recorded in
  `normalization_report.json`.
- ⛔ **NOT a trained model.** The CPU smoke test proves the pipeline runs; it does not produce a competitive
  detector. Real training is GPU-hours and is YOURS to run. A local smoke result is NOT a leaderboard result.
- ⛔ Does NOT touch the poisoned_model.pth / unlearning sub-task (out of scope — unresearched).

## Next
→ run real training on a GPU, produce `preds.csv`, then `evaluate-detection` (honest mAP) and
`make-detection-submission` (format).
"""
    with open(os.path.join(bundle, "train_scaffold_report.md"), "w") as f:
        f.write(md)


if __name__ == "__main__":
    main()
