#!/usr/bin/env python3
"""Generate a Kaggle simulation-competition submission bundle: a main.py exposing
`agent(obs, config)`, wrapped in a never-crash legal fallback + a best-effort cumulative
time guard, packaged into submission.tar.gz, with a machine-readable submission_manifest.json.

This scaffolds the INTERFACE and SAFETY WRAPPER, not the strategy. The default policy is
random-legal (immediately submittable "does it run" floor). For envs whose action is a
structured object (Orbit Wars moves, deck selection), the generated main.py has a clearly
marked TODO block to fill — it runs out of the box only for index-style action spaces.

Exit codes: 0 ok · 2 dependency/IO issue · 3 bad/missing task json · 4 refused.

NOTE: helpers here are deliberately self-contained (the plugin copies helpers byte-identical
across scripts rather than importing a shared module).
"""
import argparse
import hashlib
import json
import os
import sys
import tarfile


def die(msg, code):
    print(msg, file=sys.stderr)
    sys.exit(code)


def load_task(path):
    if not os.path.exists(path):
        die(f"task json not found: {path} — run frame-agent-task first to write agent_task.json", 3)
    try:
        with open(path) as f:
            return json.load(f)
    except Exception as e:
        die(f"could not parse {path}: {e}", 3)


# The generated main.py. Tokens %%LIKE_THIS%% are substituted (str.replace, not .format,
# to avoid clashing with the braces in the embedded Python).
MAIN_TEMPLATE = '''\
"""Kaggle simulation-competition agent — generated by scaffold-submission.
Entry point: agent(obs, config). The framework also accepts agent(obs).

SAFETY CONTRACT (do not remove):
- Never crash: any exception in your policy -> a legal fallback move is returned.
- Legal only: the chosen action is validated against the observation's legal set.
- Time: a BEST-EFFORT cumulative guard. The competition env is the real enforcer; test on it.

Fill the block marked `=== YOUR POLICY ===`. The default is random-legal (a runnable floor).
"""
import random
import time

ENV_ID = "%%ENV_ID%%"
TIMEOUT_MODEL = "%%TIMEOUT_MODEL%%"   # "episode" or "per_move"
BUDGET_MS = %%BUDGET_MS%%
OVERAGE_MS = %%OVERAGE_MS%%
LEGAL_FIELD = %%LEGAL_FIELD%%         # configured legal-move key, or None

_EPISODE_START = None  # wall-clock start of this episode (for the "episode" model)

# Common places different kaggle_environments envs stash the legal action set.
_LEGAL_CANDIDATES = ("legal_actions", "legalActions", "legal_moves", "legalMoves",
                     "available_actions", "availableActions", "actions", "action_mask")


def _as_dict(obs):
    """obs may be a dict, or a kaggle_environments Struct (attribute access)."""
    if isinstance(obs, dict):
        return obs
    out = {}
    for k in list(_LEGAL_CANDIDATES) + ["remainingOverageTime", "step"]:
        if hasattr(obs, k):
            out[k] = getattr(obs, k)
    return out


def _legal_actions(obs):
    """Best-effort: return a list of legal actions, or None if it can't be determined."""
    d = _as_dict(obs)
    keys = ([LEGAL_FIELD] if LEGAL_FIELD else []) + list(_LEGAL_CANDIDATES)
    for k in keys:
        if k and k in d and d[k] is not None:
            v = d[k]
            # action_mask style: a 0/1 (or bool) vector -> the indices that are "on".
            if k in ("action_mask",) or (isinstance(v, (list, tuple)) and v and isinstance(v[0], bool)):
                return [i for i, m in enumerate(v) if m]
            if isinstance(v, (list, tuple)):
                return list(v)
    return None


def _fallback(obs):
    """A LEGAL but typically suboptimal move — better a losing position than a crash."""
    la = _legal_actions(obs)
    if la:
        return la[0]
    return 0  # last resort for index-action envs; fill TODO for structured-action envs


def _time_left_ms(obs):
    """Best-effort remaining budget in ms. Uses the env's overage clock when present."""
    global _EPISODE_START
    d = _as_dict(obs)
    if d.get("remainingOverageTime") is not None:
        return float(d["remainingOverageTime"]) * 1000.0 + BUDGET_MS
    if TIMEOUT_MODEL == "episode":
        if _EPISODE_START is None:
            _EPISODE_START = time.time()
        used = (time.time() - _EPISODE_START) * 1000.0
        return (BUDGET_MS + OVERAGE_MS) - used
    return BUDGET_MS + OVERAGE_MS  # per_move: assume the whole budget each call


def _policy(obs, config):
    # === YOUR POLICY ===
    # Default: pick a random legal action (a runnable floor that never makes an illegal move).
    # Replace with your heuristic/search. Keep it fast: respect _time_left_ms(obs).
    #
    # TODO (structured-action envs): if this env's action is NOT a simple index
    # (e.g. Orbit Wars expects [from_planet_id, angle_radians, num_ships]; deck-selection
    # expects a list of 60 card ids), build and return that object here instead.
    la = _legal_actions(obs)
    if la:
        return random.choice(la)
    return _fallback(obs)


def agent(obs, config=None):
    try:
        # If we're nearly out of time, bail to the cheap legal move.
        if _time_left_ms(obs) <= 50:
            return _fallback(obs)
        action = _policy(obs, config)
        la = _legal_actions(obs)
        if la is not None:
            try:
                if action not in la:
                    return _fallback(obs)
            except TypeError:
                pass  # unhashable/structured action — trust the policy
        return action
    except Exception:
        return _fallback(obs)
'''


def render_main(task, policy):
    env_id = task.get("env_id") or "unknown"
    to = task.get("timeout") or {}
    model = to.get("model") or "episode"
    budget = to.get("budget_ms")
    overage = to.get("overage_ms")
    legal = task.get("legal_move_field")
    src = MAIN_TEMPLATE
    src = src.replace("%%ENV_ID%%", str(env_id))
    src = src.replace("%%TIMEOUT_MODEL%%", "per_move" if model == "per_move" else "episode")
    src = src.replace("%%BUDGET_MS%%", str(int(budget)) if isinstance(budget, (int, float)) else "1000")
    src = src.replace("%%OVERAGE_MS%%", str(int(overage)) if isinstance(overage, (int, float)) else "0")
    src = src.replace("%%LEGAL_FIELD%%", json.dumps(legal) if legal else "None")
    if policy == "first_legal":
        src = src.replace(
            "    la = _legal_actions(obs)\n    if la:\n        return random.choice(la)\n    return _fallback(obs)",
            "    return _fallback(obs)  # first-legal policy",
        )
    return src


def agent_count(env):
    """kaggle_environments env.specification.agents is a list of VALID player counts (e.g. [2] or [2, 4]),
    not the count itself. Pick the first valid count; default to 2."""
    a = getattr(env.specification, "agents", None)
    if isinstance(a, (list, tuple)) and a and isinstance(a[0], int):
        return a[0]
    if isinstance(a, int):
        return a
    return 2


def smoke_test(out_dir, env_id):
    """If kaggle_environments is installed and the env id is known, run ONE episode of
    [main.py, 'random'] to confirm the bundle loads and returns legal actions."""
    try:
        from kaggle_environments import make
    except Exception:
        return {"ran_locally": False, "reason": "kaggle_environments not installed (pip install kaggle-environments to smoke-test)"}
    if not env_id or env_id == "unknown":
        return {"ran_locally": False, "reason": "env_id unknown — cannot smoke-test"}
    main_path = os.path.join(out_dir, "main.py")
    try:
        env = make(env_id, debug=True)
        n = agent_count(env)
        agents = [main_path] + ["random"] * (n - 1)
        env.run(agents)
        states = env.steps[-1]
        statuses = [s.get("status") for s in states]
        ok = all(st in ("ACTIVE", "DONE", "INACTIVE") for st in statuses)
        return {"ran_locally": True, "final_statuses": statuses, "ok": ok}
    except Exception as e:
        return {"ran_locally": True, "ok": False, "error": f"{type(e).__name__}: {e}"}


def sha256_of(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def main():
    ap = argparse.ArgumentParser(description="Scaffold a Kaggle simulation-competition submission bundle.")
    ap.add_argument("--task-json", default="agent_task.json", help="agent_task.json from frame-agent-task")
    ap.add_argument("--out-dir", default=None, help="output bundle dir (default: <env_id>_submission)")
    ap.add_argument("--policy", choices=["random_legal", "first_legal"], default="random_legal")
    ap.add_argument("--no-package", action="store_true", help="skip building submission.tar.gz")
    ap.add_argument("--force", action="store_true", help="overwrite an existing main.py")
    args = ap.parse_args()

    task = load_task(args.task_json)
    if (task.get("runtime") or "").lower() == "custom":
        die("runtime is 'custom' (not kaggle_environments). This scaffold targets kaggle_environments; "
            "use the competition's own starter code for a custom runtime.", 4)

    env_id = task.get("env_id") or "unknown"
    out_dir = args.out_dir or f"{env_id}_submission"
    os.makedirs(out_dir, exist_ok=True)
    main_path = os.path.join(out_dir, "main.py")
    if os.path.exists(main_path) and not args.force:
        die(f"{main_path} exists — pass --force to overwrite (it may hold your policy).", 4)

    with open(main_path, "w") as f:
        f.write(render_main(task, args.policy))

    smoke = smoke_test(out_dir, env_id)

    tar_path = None
    if not args.no_package:
        tar_path = os.path.join(out_dir, "submission.tar.gz")
        with tarfile.open(tar_path, "w:gz") as tar:
            tar.add(main_path, arcname="main.py")  # main.py at the ROOT of the archive

    manifest = {
        "bundle_path": os.path.abspath(tar_path) if tar_path else os.path.abspath(out_dir),
        "entry_point": "main.py",
        "agent_signatures": ["agent(obs)", "agent(obs, config)"],
        "env_id": env_id,
        "policy": args.policy,
        "fallback": "first_legal",
        "time_guard": {"model": (task.get("timeout") or {}).get("model", "episode"),
                       "budget_ms": (task.get("timeout") or {}).get("budget_ms")},
        "packaging": "tar.gz" if tar_path else "dir",
        "files": ["main.py"],
        "sha256_main": sha256_of(main_path),
        "ran_locally": smoke.get("ran_locally", False),
        "smoke": smoke,
        "notes": "Scaffolds interface + safety wrapper only; default policy is random-legal. "
                 "Structured-action envs need the marked TODO filled. Test on the competition's harness before submitting.",
    }
    with open(os.path.join(out_dir, "submission_manifest.json"), "w") as f:
        json.dump(manifest, f, indent=2)

    # Human report (Mermaid-led, per house convention).
    smoke_line = ("not run (kaggle_environments missing or env unknown)" if not smoke.get("ran_locally")
                  else ("✅ ran, returned legal actions" if smoke.get("ok") else f"⚠️ ran but errored: {smoke.get('error') or smoke.get('final_statuses')}"))
    report = f"""# Submission scaffold — {env_id}

## At a glance
```mermaid
flowchart LR
    OBS["obs"] --> A["agent(obs, config)"]
    A --> TG["time guard<br/>{manifest['time_guard']['model']} {manifest['time_guard']['budget_ms']}ms"]
    TG --> POL["policy: {args.policy}"]
    POL --> VAL["validate legal"]
    VAL -->|illegal/exception| FB["first-legal fallback"]
    VAL -->|ok| OUT["action"]
    FB --> OUT
```

**Bundle:** `{manifest['bundle_path']}` · entry `main.py` at archive root · sha256 `{manifest['sha256_main'][:12]}…`
**Local smoke test:** {smoke_line}

## What this is / isn't
- ✅ A submittable bundle whose agent **never crashes** and **always returns a legal action** for index-style action spaces.
- ✅ A best-effort **cumulative** time guard (the competition env is the real enforcer — test there).
- ⚠️ The default policy is **random-legal** — a floor, not a strategy. Replace the `=== YOUR POLICY ===` block.
- ⚠️ **Structured-action envs** (Orbit Wars moves, deck selection) need the marked `TODO` filled before the agent plays meaningfully.

## Next
→ `baseline-agent` (drop in a heuristic + measure it vs random, with a crash/timeout health check).
"""
    with open(os.path.join(out_dir, "submission_report.md"), "w") as f:
        f.write(report)

    print(f"Wrote {main_path}, submission_manifest.json"
          + (f", {os.path.basename(tar_path)}" if tar_path else "")
          + f", submission_report.md in {out_dir}/")
    print(f"Local smoke test: {smoke_line}")
    if not smoke.get("ran_locally"):
        print("  (install kaggle-environments and re-run, or test on Kaggle, before trusting the bundle)")


if __name__ == "__main__":
    main()
